# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" , "dev"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: pip install requests
    - name: Install xcode-install
      run: gem install xcode-install
    - name: Build and Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CORRECT_COVERAGE: ${{ secrets.CORRECT_COVERAGE }}
        FRAMEWORK_NAME: FoundationX
      run: |
        xcrun llvm-cov export -format="lcov" .build/debug/${{FRAMEWORK_NAME}}PackageTests.xctest/Contents/MacOS/${{FRAMEWORK_NAME}}PackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
        curl -Os https://uploader.codecov.io/latest/macos/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
        python request.py
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
