# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" , "dev"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: pip install requests
    - name: Install xcode-install
      run: gem install xcode-install
    - name: Test
      run: swift test --enable-code-coverage
      uses: michaelhenry/swifty-code-coverage@v1.0.0
        with:
          build-path: .build
          target: FoundationX.xctest
          is-spm: true
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
