# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Lint & Test Package

on:
  push:
    branches: [ "master" , "dev"]
  pull_request:
    branches: [ "master" ]

jobs:
  PodLint:
    name: Cocoapods Lint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cocoapods
        run: gem install cocoapods --no-document --quiet
      
      - name: Lint
        run: |
          set -o pipefail
          pod lib lint --allow-warnings

  build:
    runs-on: macos-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - run: swift test --enable-code-coverage
      - uses: Lguanghui/swifty-code-coverage@1.0.0
        with:
          build-path: .build
          target: FoundationXPackageTests.xctest
          is-spm: true

      - name: Upload to Codecov
        run: |
          bash <(curl https://codecov.io/bash) -f "coverage/*.info"
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV }}
