# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" , "dev"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: pip install requests
    - name: Install xcode-install
      run: gem install xcode-install
    - name: Build and Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CORRECT_COVERAGE: ${{ secrets.CORRECT_COVERAGE }}
        FRAMEWORK_NAME: FoundationX
      run: |
        swift test --enable-code-coverage
        xcrun llvm-cov export -format="lcov" .build/debug/{{ env.FRAMEWORK_NAME }}PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
