name: Update CHANGELOG.md Automaticly

on:
  push:
    tags:
      - "**"

jobs:
  update_changelog:
      name: Update CHANGELOG.md
      runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install git-chglog
          run: |
            brew tap git-chglog/git-chglog
            brew install git-chglog
        - name: Generate CHANGELOG.md
          run: |
            git-chglog -o CHANGELOG.md
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            assignees: Lguanghui
            reviewers: Lguanghui
            commit-message: 'chore(ci): auto update CHANGELOG.md ${date}'
            branch: ci-update-changelog-patches
            delete-branch: true
            title: '[CI] Auto Update CHANGELOG.md'
            body: |
              Update report
              - Updated with *today's* date
              - Auto-generated by [create-pull-request][1]
            labels: |
              [ci]auto_update
              
#         deprecated due to `master` is a protected branch
#         - name: Commit & Push changes
#           uses: actions-js/push@master
#           with:
#             github_token: ${{ secrets.GITHUB_TOKEN }}
#             branch: 'master'
#             message: 'chore(ci): auto update CHANGELOG.md ${date}'
